#
version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.9.4
     environment:
        - SFDX_URL_LINUX=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        - SFDX_AUTOUPDATE_DISABLE=true
        - SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
        - SFDX_DOMAIN_RETRY=300

     steps:
       - checkout
       - run: npm install
       - run: sudo npm install -g junit-merge
       - run: npm compile
       - run: npm run test:unit
       - run: junit-merge -d packages -r -C -o junit-results/junit.xml junit-custom.xml
       - store_test_results:
          path: ~/junit-results/
       - store_artifacts:
          path: ~/junit-results/
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
                - master
    jobs:
      - build
